# Generated by Django 4.1.4 on 2022-12-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Audiovisual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('visualizaciones', models.PositiveIntegerField(default=0)),
                ('puntaje', models.PositiveSmallIntegerField(default=1)),
                ('generos', models.ManyToManyField(to='streaming.genero')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.tipo')),
            ],
        ),
    ]
